steps:
  # Step to install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step to generate the Prisma client
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'prisma:generate']

  # Step to build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step to deploy to Google App Engine (or other services)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

options:
  # Set the logging option (Choose the logging method)
  logging: CLOUD_LOGGING_ONLY

# Timeout for the build process (20 minutes)
timeout: '1200s'
